<?php
include("textbox.js");
include("combobox.js");
include("connectioncombobox.js");
include("databasecombobox.js");
include("form.js");
include("floatingform.js");
include("queryform.js");
include("addquerytabform.js");
include("connectionform.js");
?>