<?php
include("bar.js");
include("menubar.js");
include("toolbar.js");
include("connectiontreetoolbar.js");
include("querytabstatusbar.js");
include("maintoolbar.js");
include("resultgridpagingtoolbar.js");
?>